inherit_from:
  - .rubocop_airbnb.yml

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'

Rails/HelperInstanceVariable:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Airbnb/RiskyActiverecordInvocation:
  Enabled: false

Metrics/LineLength:
  Max: 160